---
abstract: 'Token bucket rate limiting algorithm'
author:
  - 'Alex Kapranoff, E<lt>kappa@cpan.orgE<gt>'
build_requires:
  Test::NoWarnings: 0
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-TokenBucket
provides:
  Algorithm::TokenBucket:
    file: lib/Algorithm/TokenBucket.pm
    version: 0.36
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/kapp/algorithm-tokenbucket
version: 0.36
